### ISSUE TITLE
Elections do not save votes

### ISSUE THREAD

**Issue by subversiveasset** [julien-boudry/Condorcet.Vote#3]
When adding/editing votes on Condorcet.Vote, the votes are not processed. The site will say that the votes were recorded, but no condorcet winner will be chosen, and upon a refresh of the page, the votes will reduce to 0.

**Comment by subversiveasset** [comment]
Hmm, there's another issue. In the previous editions of Condorcet.Vote, improperly formatted votes would not register as accepted. (The site would just go to the edit page without having text at the top of the page saying the vote was accepted.)

In the latest version of Condorcet.Vote, the site says that the vote is accepted, but rejects the vote.

(However, as far as I can tell, properly formatted votes are still rejected).

**Comment by julien-boudry** [comment]
So we have two good different problems to deal with.

The first is an extremely intriguing cache bug. The cache is on the side of the Condorcet library, but impossible to reproduce with it alone. There is really a particular case on Condorcet.Vote, very strange.

It is clear that the votes are recorded, but the results are not updated.

I found how to hotfix it, but I prefer to continue looking for a real solution. Because that worries me a lot.

I move the second one to another ticket, less urgent.

**Comment by julien-boudry** [comment]
Very nice bug, very vicious.

Fix will be deploy live on www.Condorcet.Vote on Wednesday 04/04.

**Comment by julien-boudry** [comment]
Correction is live on www.condorcet.vote

All results were newly recalculated. All votes are preserved.

**Comment by subversiveasset** [comment]
I can verify that results now calculate properly and votes are preserved.
